baseurl = "https://example.org/"
languageCode = "en-us"
title = "John Doe's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
themesDir = "../.."

[params]
    site_author = "John Doe"
    site_description = "The awesome blog of John Doe."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Customizable header title"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "spf13"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "digitalcraftsman"
    gplus     = ""

[[menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Tags"
    weight = -90
    identifier = "tags"
    url = "#"

[[menu.main]]
    name = "Hugo"
    parent = "tags"
    weight = -99
    identifier = "hugo"
    url = "/tags/hugo/"

[[menu.main]]
    name = "Jekyll"
    parent = "tags"
    weight = -98
    identifier = "jekyll"
    url = "/tags/jekyll/"

[[menu.main]]
    name = "Migration"
    parent = "tags"
    weight = -97
    identifier = "migration"
    url = "/tags/migration/"

[[menu.main]]
    name = "Articles"
    weight = -80
    identifier = "articles"
    url = "#"

[[menu.main]]
    name = "Creating a new theme"
    parent = "articles"
    weight = -89
    identifier = "creating-a-new-theme"
    url = "/post/creating-a-new-theme/"

[[menu.main]]
    name = "Go is for lovers"
    parent = "articles"
    weight = -88
    identifier = "go-is-for-lovers"
    url = "/post/go-is-for-lovers/"

[[menu.main]]
    name = "Hugo is for lovers"
    parent = "articles"
    weight = -87
    identifier = "hugo-is-for-lovers"
    url = "/post/hugo-is-for-lovers/"

[[menu.main]]
    name = "Migrate from jekyll"
    parent = "articles"
    weight = -86
    identifier = "migrate-from-jekyll"
    url = "/post/migrate-from-jekyll/"
